baseURL = 'https://ojack.xyz/hydra-blog'
languageCode = 'en-us'
title = 'hydra video synth'
theme = "hugo-book"
enableGitInfo = true

[markup.goldmark.renderer]
 unsafe = true

[languages]
[languages.en]
  languageName = 'English'
  contentDir = 'content'
  weight = 1
[languages.ja]
  languageName = '日本語'
  contentDir = 'content.ja'
  weight = 2


[menu]
# [[menu.before]]
# [[menu.after]]
 # name = "web editor"
 # url = "https://hydra.ojack.xyz"
 # name = "Github"
 # url = "https://github.com/hydra-synth/hydra-blog"
 # weight = 10

[[menu.after]]
  name = "contribute"
  url = "https://opencollective.com/hydra-synth"

[[menu.after]]
  name = "grants"
  url = "https://hydra.ojack.xyz/grants"

[[menu.after]]
  name = "showcase"
  url = "https://hydra.ojack.xyz/garden"

[params]
  # Set source repository location.
  # Used for 'Last Modified' and 'Edit this page' links.
  BookRepo = 'https://github.com/ojack/hydra-blog'

  # (Optional, default 'commit') Specifies commit portion of the link to the page's last modified
  # commit hash for 'doc' page type.
  # Requires 'BookRepo' param.
  # Value used to construct a URL consisting of BookRepo/BookCommitPath/<commit-hash>
  # Github uses 'commit', Bitbucket uses 'commits'
  # BookCommitPath = 'commit'

  # Enable "Edit this page" links for 'doc' page type.
  # Disabled by default. Uncomment to enable. Requires 'BookRepo' param.
  # Edit path must point to root directory of repo.
  BookEditPath = 'edit/main'

  # Configure the date format used on the pages
  # - In git information
  # - In blog posts
  BookDateFormat = 'January 2, 2006'

  # BookMenuBundle = '/menu'